SELECT DISTINCT CITY
FROM STATION
WHERE UPPER(SUBSTR(CITY, 1, 1)) NOT IN ('A', 'E', 'I', 'O', 'U')
OR UPPER(SUBSTR(CITY, LENGTH(CITY), 1)) NOT IN ('A', 'E', 'I', 'O', 'U');



-- SELECT DISTINCT CITY FROM STATION WHERE upper(SUBSTR(CITY,1,1)) 
-- NOT IN ('A','E','I','O','U') AND
-- upper(SUBSTR(CITY,-1,1)) NOT IN ('A','E','I','O','U');     
